// Generated by React Router
import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:project.csv": {
    params: {
      project: string;
    };
  };
  "/projects/:project": {
    params: {
      project: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects" | "/projects/:project.csv" | "/projects/:project";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects" | "/projects/:project.csv" | "/projects/:project";
  };
  "routes/projects.$project[.csv].tsx": {
    id: "routes/projects.$project[.csv]";
    page: "/projects/:project.csv";
  };
  "routes/projects.$project.tsx": {
    id: "routes/projects.$project";
    page: "/projects/:project";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};
